### ISSUE TITLE
add Password verification button

### ISSUE THREAD

**Issue by AntonH-dev** [Vluurie/NextVertretung#1]
Please add a button where you can see what you entered as a password. So I would like to remove the dots for a moment and see the password.

**Comment by EczoTV** [comment]
The reaseon: I cant login

**Comment by Vluurie** [comment]
> Please add a button where you can see what you entered as a password. So I would like to remove the dots for a moment and see the password.

Thanks for your report. Will get to the TODO features list

**Comment by Vluurie** [comment]
solved with last merge development into main (made it 3s then it hides again)
